### ISSUE TITLE
Expression: ("libev: fd >= FD_SETSIZE passed to fd_set-based select backend", fd < FD_SETSIZE)

### ISSUE THREAD

**Issue by HHA-MNK** [lazytinker/ntripcaster#2]
17:01:50.675 [TRACE] ntripcaster.c:630: -----------------------------------------------
17:01:58.150 [INFO ] ntripcaster.c:504: agent(320) connection close
17:01:58.150 [INFO ] ntripcaster.c:145: close agent(320) from 192.168.0.30
17:02:00.674 [TRACE] ntripcaster.c:610: ======= Current clients/servers status ========
17:02:00.674 [TRACE] ntripcaster.c:611: Type     MountP   From             Bps   Bytes    UserAgent
17:02:00.674 [TRACE] ntripcaster.c:621: Source   T111V    192.168.0.233    1032  119554    NTRIP RTKLIB/2.4.2
17:02:00.674 [TRACE] ntripcaster.c:617: Client   T111V    192.168.0.126    1032  119554   NTRIP 1.00.230404.DecoderGNSS.G992B221013277302
17:02:00.674 [TRACE] ntripcaster.c:630: -----------------------------------------------
17:02:08.159 [INFO ] ntripcaster.c:565: accept agent(340) from 192.168.0.30:64124
17:02:08.169 [INFO ] ntripcaster.c:460: move agent(340) into source agents
17:02:10.674 [TRACE] ntripcaster.c:610: ======= Current clients/servers status ========
17:02:10.674 [TRACE] ntripcaster.c:611: Type     MountP   From             Bps   Bytes    UserAgent
17:02:10.675 [TRACE] ntripcaster.c:621: Source   T111V    192.168.0.233    1032  131121    NTRIP RTKLIB/2.4.2
17:02:10.675 [TRACE] ntripcaster.c:621: Source   T000V    192.168.0.30     0     0         NTRIP RTKLIB/2.4.2
17:02:10.675 [TRACE] ntripcaster.c:617: Client   T111V    192.168.0.126    1032  131121   NTRIP 1.00.230404.DecoderGNSS.G992B221013277302
17:02:10.675 [TRACE] ntripcaster.c:630: -----------------------------------------------
17:02:18.188 [INFO ] ntripcaster.c:504: agent(340) connection close
17:02:18.188 [INFO ] ntripcaster.c:145: close agent(340) from 192.168.0.30
17:02:20.675 [TRACE] ntripcaster.c:610: ======= Current clients/servers status ========
17:02:20.675 [TRACE] ntripcaster.c:611: Type     MountP   From             Bps   Bytes    UserAgent
17:02:20.675 [TRACE] ntripcaster.c:621: Source   T111V    192.168.0.233    1032  142688    NTRIP RTKLIB/2.4.2
17:02:20.675 [TRACE] ntripcaster.c:617: Client   T111V    192.168.0.126    1032  142688   NTRIP 1.00.230404.DecoderGNSS.G992B221013277302
17:02:20.675 [TRACE] ntripcaster.c:630: -----------------------------------------------
17:02:28.191 [INFO ] ntripcaster.c:565: accept agent(320) from 192.168.0.30:64357
Assertion failed!

Program: D:\software\ntrip_caster\ntripcaster.exe
File: E:\Develop\ntripcaster\libev/ev_select.c, Line 85

Expression: ("libev: fd >= FD_SETSIZE passed to fd_set-based select backend", fd < FD_SETSIZE)

After running for 20 minutes in the Windows 11 environment, the program will experience an exception.

**Comment by tisyang** [comment]
For windows, this project is only just works. 
It it hard to maintain for compatiblity in `MinGW`(maybe also `libev`) with Windows, worse since Win10/Win11. MS has changed so many API's compatiblity.

You can choose the linux build, or just in WSL, and try again.
