### ISSUE TITLE
NTRIP VERSION

### ISSUE THREAD

**Issue by obedmacallums** [lazytinker/ntripcaster#3]
Hello tisyang, is the software only for ntrip version 1.0, right?

**Comment by tisyang** [comment]
@obedmacallums yes, only support ntrip protocol 1.0.

**Comment by obedmacallums** [comment]
is there any way to send config by ENV variables? I want to build it inside a docker container

**Comment by tisyang** [comment]
@obedmacallums You can use this docker image [rinex20/another_ntripcaster](https://hub.docker.com/r/rinex20/another_ntripcaster), it's base on this repo. Or you can use mount entry of docker similarly.
