### ISSUE TITLE
我该如何判断我部署的服务是否成功

### ISSUE THREAD

**Issue by a2541644892** [lazytinker/ntripcaster#4]
作者您好，我该如何判断我部署的服务是否成功，有无验证工具这类的？

**Comment by tisyang** [comment]
@a2541644892  用 rtklib 的工具 str2str 或 界面程序都可以，本质就是用 ntrip 客户端去测试实验。

另外，如果部署完成且有 ntrip source 数据发送到服务器，则用浏览器打开服务端口网页会显示已经上传的 sourcetable 列表。

**Comment by xuxiuzhi2627** [comment]
连接成功网页上是显示如下信息吗？
SOURCETABLE 200 OK
Server: ntripcaster
Date: Thu Aug  8 11:16:16 2024 UTC
Connection: close
Content-Type: text/plain
Content-Length: 119

STR;RTCM32;RTCM32;RTCM32;1005(10),1074-1084-1124(1);2;GNSS;NET;CHN;0.00;0.00;1;0;None;None;B;N;1336;
ENDSOURCETABLE

**Comment by tisyang** [comment]
是的，这个网页会显示当前的 SOURCETABLE 列表，你这个显示已经有一个 RTCM32 的挂载点在传输数据，比特率约在 1336 bps.

xuxiuzhi2627 ***@***.***> 于2024年8月8日周四 19:20写道：
