### ISSUE TITLE
ntripcaster使用问题

### ISSUE THREAD

**Issue by xuxiuzhi2627** [lazytinker/ntripcaster#5]
您好，我在使用ntripcaster工具中遇到一些问题，想咨询您一下，
（1）ntripcaster.json文件中一个tokens_source对应一个tokens_client吗？不能使用一个tokens_source，给多个tokens_client发送数据吗？
（2）tokens_client的用户名和密码必须是tokens_source的密码吗?用户名和密码的命令和tokens_source有什么关系吗？
期望收到您的回复

**Comment by tisyang** [comment]
@xuxiuzhi2627 ntrip 协议分为三大角色，source/client/caster， source 是给 caster 上传源数据的，client 是从 caster 获取数据的，caster 是给彼此交换数据的服务角色。所以对应的有 source 的 token，也就是上传密码，对应 client 的用户名密码对。

token_source 对应的就是 source 的密码对组，token_client 是 client 的用户名密码对组，都是锚定挂载点设定的。两者都是 Json object, 允许每个挂载点设定用户名密码，也可以使用通配符 * 来通配所有挂载点。
