### ISSUE TITLE
client定位解的状态和位置信息

### ISSUE THREAD

**Issue by xuxiuzhi2627** [lazytinker/ntripcaster#6]
您好，如果我想解析收到的查分数据，得到client定位解的状态和实时位置信息，该在哪里修改呢？收到的差分数据是保存在agent_reab_cb函数的buf里吗？

**Comment by tisyang** [comment]
> 您好，如果我想解析收到的查分数据，得到client定位解的状态和实时位置信息，该在哪里修改呢？收到的差分数据是保存在agent_reab_cb函数的buf里吗？


你可以参考 

https://github.com/tisyang/cors-relay/blob/master/ntripcaster.c#L219-L219

**Comment by xuxiuzhi2627** [comment]
好的，非常感谢

**Comment by xuxiuzhi2627** [comment]
> > 您好，如果我想解析收到的查分数据，得到client定位解的状态和实时位置信息，该在哪里修改呢？收到的差分数据是保存在agent_reab_cb函数的buf里吗？
> 
> 你可以参考
> 
> https://github.com/tisyang/cors-relay/blob/master/ntripcaster.c#L219-L219

好的，非常感谢！
