### ISSUE TITLE
位置信息

### ISSUE THREAD

**Issue by xuxiuzhi2627** [lazytinker/ntripcaster#7]
你好，我不知道怎么修改代码，是在哪个函数里修改，现在的ntripcaster是不是没有收到gga数据，若没有收到，应该怎么修改代码呢？可加我vx xxz52lxw，可有偿咨询，非常感谢

**Comment by tisyang** [comment]
https://github.com/tisyang/ntripcaster/blob/cc1792917e2624247fc40639c117c33cbd24e4cc/ntripcaster.c#L470

在这里修改，去参考 cors-relay 对应的代码即可
