### ISSUE TITLE
Base会出现偶发的收不到接受机的数据

### ISSUE THREAD

**Issue by xuxiuzhi2627** [lazytinker/ntripcaster#9]
Base用户作为ntripserver时，会出现偶发的收不到接受机的数据，若想知道是网络原因还是接收机设备问题导致的，有什么好的方法吗？我看到在if (now - agent->last_activity >= 60.0)代码附近进行了判断，这个是因为网络原因导致的收不到数据吗？

**Comment by tisyang** [comment]
@xuxiuzhi2627 优先排查网络问题。这里的代码只是做超时判断的，如果连接没有数据收发超过 1min, 那么就会踢出这个连接回收。如果你有这样的问题，建议先查看日志。

**Comment by xuxiuzhi2627** [comment]
是用ping直接看接收机上是否丢包这样查看网络原因吗？

**Comment by tisyang** [comment]
@xuxiuzhi2627 直接去看 ntripserver 的输出，看看连接有没有异常
